### PR TITLE
Update some changes and some instruction

### PR DESCRIPTION
**Pull request by Mujammil-ios**
As i show your code project. I think it's good practice to use splash screen in android projects.

### CODE REVIEW

**Review by Mujammil-ios — COMMENTED** [review]
It up to date code it can be pushed.

**Comment by bystrovdev** [comment]
> As i show your code project. I think it's good practice to use splash screen in android projects.

Thank you for the information about the screen saver, I will follow your advice in future updates.

**Review by bystrovdev — APPROVED** [review]
Added filename string

**Review by Mujammil-ios — COMMENTED** [review]
Update

**Comment by bystrovdev** [comment]
> Update

Updated changes

**Pull request closed without merging**
